Repository Iduk-Baduk/itseats-server, pull requests merged in 2025-07, with the labels that each got.

#161 [Chore] Github Actions 설정
  .github/workflows/gradle.yml
  .gitignore
  gradle/wrapper/gradle-wrapper.jar
  gradlew
  gradlew.bat
Labels: chore

#153 [Fix] 주문 생성 관련 오류 수정
  src/main/java/com/idukbaduk/itseats/order/entity/Order.java
  src/main/java/com/idukbaduk/itseats/order/service/OrderService.java
Labels: bug

#162 [Feature] 주문 재개 API 구현
  src/main/java/com/idukbaduk/itseats/store/controller/OwnerStoreController.java
  src/main/java/com/idukbaduk/itseats/store/service/OwnerStoreService.java
  src/test/java/com/idukbaduk/itseats/store/controller/OwnerStoreControllerTest.java
  src/test/java/com/idukbaduk/itseats/store/service/OwnerStoreServiceTest.java
Labels: feature

#164 [Feature] 예상 조리시간 설정 API 구현
  src/main/java/com/idukbaduk/itseats/order/controller/OwnerOrderController.java
  src/main/java/com/idukbaduk/itseats/order/dto/CookTimeRequest.java
  src/main/java/com/idukbaduk/itseats/order/dto/CookTimeResponse.java
  src/main/java/com/idukbaduk/itseats/order/dto/enums/OrderResponse.java
  src/main/java/com/idukbaduk/itseats/order/entity/Order.java
  src/main/java/com/idukbaduk/itseats/order/service/OwnerOrderService.java
  src/test/java/com/idukbaduk/itseats/order/controller/OwnerOrderControllerTest.java
  src/test/java/com/idukbaduk/itseats/order/service/OwnerOrderServiceTest.java
Labels: feature

#170 [Feature] 주소 관리 CRUD API 구현
  src/main/java/com/idukbaduk/itseats/memberaddress/controller/MemberAddressController.java
  src/main/java/com/idukbaduk/itseats/memberaddress/dto/AddressResponse.java
  src/main/java/com/idukbaduk/itseats/memberaddress/dto/enums/AddressResponse.java
  src/main/java/com/idukbaduk/itseats/memberaddress/entity/MemberAddress.java
  src/main/java/com/idukbaduk/itseats/memberaddress/repository/MemberAddressRepository.java
  src/main/java/com/idukbaduk/itseats/memberaddress/service/MemberAddressService.java
  src/test/java/com/idukbaduk/itseats/memberaddress/service/MemberAddressServiceTest.java
Labels: feature

#179 refactor: 메뉴 옵션 조회 엔드포인트 변경
  src/main/java/com/idukbaduk/itseats/menu/controller/UserMenuController.java
Labels: refactor

#177 [Refactor] 통계 처리 로직 Redis 캐시 적용
  src/main/java/com/idukbaduk/itseats/review/dto/StoreReviewStats.java
  src/main/java/com/idukbaduk/itseats/review/service/ReviewStatsService.java
  src/main/java/com/idukbaduk/itseats/store/service/StoreService.java
Labels: refactor

#174 [Feature] 리뷰 작성 API 구현
  src/main/java/com/idukbaduk/itseats/review/controller/ReviewController.java
  src/main/java/com/idukbaduk/itseats/review/dto/ReviewCreateRequest.java
  src/main/java/com/idukbaduk/itseats/review/dto/ReviewCreateResponse.java
  src/main/java/com/idukbaduk/itseats/review/dto/enums/ReviewResponse.java
  src/main/java/com/idukbaduk/itseats/review/service/ReviewService.java
  src/test/java/com/idukbaduk/itseats/review/controller/ReviewControllerTest.java
  src/test/java/com/idukbaduk/itseats/review/service/ReviewServiceTest.java
Labels: feature

#183 chore: access-token 헤더 CORS 설정
  src/main/java/com/idukbaduk/itseats/global/config/CorsConfig.java
Labels: chore

#189 [Refactor] StoreService Redis 캐시 적용
  src/main/java/com/idukbaduk/itseats/review/service/ReviewStatsService.java
  src/main/java/com/idukbaduk/itseats/store/service/StoreService.java
  src/test/java/com/idukbaduk/itseats/store/service/StoreServiceTest.java
Labels: refactor

#185 [Feature] 특정 기간 내 가게 별 리뷰 조회 API 구현
  src/main/java/com/idukbaduk/itseats/review/controller/OwnerReviewController.java
  src/main/java/com/idukbaduk/itseats/review/dto/ReviewDto.java
  src/main/java/com/idukbaduk/itseats/review/dto/ReviewListResponse.java
  src/main/java/com/idukbaduk/itseats/review/dto/enums/ReviewResponse.java
  src/main/java/com/idukbaduk/itseats/review/repository/ReviewImageRepository.java
  src/main/java/com/idukbaduk/itseats/review/repository/ReviewRepository.java
  src/main/java/com/idukbaduk/itseats/review/service/OwnerReviewService.java
  src/main/java/com/idukbaduk/itseats/store/error/enums/StoreErrorCode.java
  src/test/java/com/idukbaduk/itseats/review/controller/OwnerReviewControllerTest.java
  src/test/java/com/idukbaduk/itseats/review/service/OwnerReviewServiceTest.java
Labels: feature

#187 [Feature] 악성 리뷰 신고 API 구현
  src/main/java/com/idukbaduk/itseats/review/controller/OwnerReviewController.java
  src/main/java/com/idukbaduk/itseats/review/dto/ReviewReportRequest.java
  src/main/java/com/idukbaduk/itseats/review/dto/ReviewReportResponse.java
  src/main/java/com/idukbaduk/itseats/review/dto/enums/ReviewResponse.java
  src/main/java/com/idukbaduk/itseats/review/entity/ReviewReport.java
  src/main/java/com/idukbaduk/itseats/review/entity/enums/ReportStatus.java
  src/main/java/com/idukbaduk/itseats/review/error/ReviewErrorCode.java
  src/main/java/com/idukbaduk/itseats/review/repository/ReviewReportRepository.java
  src/main/java/com/idukbaduk/itseats/review/service/OwnerReviewService.java
  src/test/java/com/idukbaduk/itseats/review/controller/ReviewReportControllerTest.java
  src/test/java/com/idukbaduk/itseats/review/service/ReviewReportServiceTest.java
Labels: feature

#204 [Feature] 더미데이터 생성을 위한 이미지 링크 업로드 기능
  src/main/java/com/idukbaduk/itseats/menu/service/MenuMediaService.java
  src/main/java/com/idukbaduk/itseats/store/service/StoreMediaService.java
Labels: feature

#211 [Refactor] Order 리팩토링
  src/main/java/com/idukbaduk/itseats/order/controller/OwnerOrderController.java
  src/main/java/com/idukbaduk/itseats/order/entity/Order.java
  src/main/java/com/idukbaduk/itseats/order/repository/OrderRepository.java
  src/main/java/com/idukbaduk/itseats/order/service/OrderService.java
  src/main/java/com/idukbaduk/itseats/order/service/OwnerOrderService.java
  src/main/java/com/idukbaduk/itseats/order/service/RiderOrderService.java
  src/main/java/com/idukbaduk/itseats/store/repository/StoreRepository.java
  src/test/java/com/idukbaduk/itseats/order/controller/OwnerOrderControllerTest.java
  src/test/java/com/idukbaduk/itseats/order/service/OrderServiceTest.java
  src/test/java/com/idukbaduk/itseats/order/service/OwnerOrderServiceTest.java
Labels: refactor

#217 [Refactor] OrderReceptionResponse에 orderId 필드 추가
  src/main/java/com/idukbaduk/itseats/order/dto/OrderReceptionResponse.java
  src/main/java/com/idukbaduk/itseats/order/service/OwnerOrderService.java
Labels: refactor

#200 [Refactor] 주문 시 쿠폰 적용
  src/main/java/com/idukbaduk/itseats/coupon/error/CouponException.java
  src/main/java/com/idukbaduk/itseats/coupon/error/enums/CouponErrorCode.java
  src/main/java/com/idukbaduk/itseats/coupon/service/CouponPolicyService.java
  src/main/java/com/idukbaduk/itseats/order/dto/OrderNewRequest.java
  src/main/java/com/idukbaduk/itseats/order/service/OrderService.java
  src/test/java/com/idukbaduk/itseats/order/service/OrderServiceTest.java
Labels: refactor

#193 [Feature] 토스페이먼츠 결제 연동 및 토스 결제 승인 API 구현
  src/main/java/com/idukbaduk/itseats/global/config/ClientConfig.java
  src/main/java/com/idukbaduk/itseats/payment/controller/PaymentController.java
  src/main/java/com/idukbaduk/itseats/payment/dto/PaymentClientResponse.java
  src/main/java/com/idukbaduk/itseats/payment/dto/PaymentConfirmRequest.java
  src/main/java/com/idukbaduk/itseats/payment/dto/PaymentInfoRequest.java
  src/main/java/com/idukbaduk/itseats/payment/dto/enums/PaymentResponse.java
  src/main/java/com/idukbaduk/itseats/payment/entity/Payment.java
  src/main/java/com/idukbaduk/itseats/payment/entity/enums/PaymentStatus.java
  src/main/java/com/idukbaduk/itseats/payment/error/enums/PaymentConfirmErrorCode.java
  src/main/java/com/idukbaduk/itseats/payment/error/enums/PaymentErrorCode.java
  src/main/java/com/idukbaduk/itseats/payment/repository/PaymentRepository.java
  src/main/java/com/idukbaduk/itseats/payment/service/PaymentService.java
  src/main/java/com/idukbaduk/itseats/payment/service/client/PaymentClient.java
  src/test/java/com/idukbaduk/itseats/payment/service/PaymentServiceTest.java
Labels: feature

#205 [Refactor] 결제 시 쿠폰 적용
  src/main/java/com/idukbaduk/itseats/coupon/entity/MemberCoupon.java
  src/main/java/com/idukbaduk/itseats/coupon/repository/MemberCouponRepository.java
  src/main/java/com/idukbaduk/itseats/coupon/repository/PaymentCouponRepository.java
  src/main/java/com/idukbaduk/itseats/coupon/service/CouponPolicyService.java
  src/main/java/com/idukbaduk/itseats/payment/dto/PaymentInfoRequest.java
  src/main/java/com/idukbaduk/itseats/payment/service/PaymentService.java
  src/test/java/com/idukbaduk/itseats/payment/service/PaymentServiceTest.java
Labels: refactor

#220 [Fix] 주문 접수화면 주문 조회 로직 수정
  src/main/java/com/idukbaduk/itseats/order/repository/OrderRepository.java
Labels: fix

#190 [Feature] 대기 배달 주문 조회 API 구현
  src/main/java/com/idukbaduk/itseats/memberaddress/entity/MemberAddress.java
  src/main/java/com/idukbaduk/itseats/order/dto/NearbyOrderDTO.java
  src/main/java/com/idukbaduk/itseats/order/entity/Order.java
  src/main/java/com/idukbaduk/itseats/order/repository/OrderRepository.java
  src/main/java/com/idukbaduk/itseats/rider/controller/RiderController.java
  src/main/java/com/idukbaduk/itseats/rider/dto/NearByOrderRequest.java
  src/main/java/com/idukbaduk/itseats/rider/dto/ReadyOrderResponse.java
  src/main/java/com/idukbaduk/itseats/rider/dto/enums/RiderResponse.java
  src/main/java/com/idukbaduk/itseats/rider/error/enums/RiderErrorCode.java
  src/main/java/com/idukbaduk/itseats/rider/service/RiderService.java
  src/main/java/com/idukbaduk/itseats/store/entity/Store.java
  src/test/java/com/idukbaduk/itseats/rider/service/FindNearbyOrdersServiceTest.java
  src/test/java/com/idukbaduk/itseats/rider/service/RiderServiceTest.java
Labels: feature

#209 [Feature] 내 쿠폰목록 조회 API 구현
  src/main/java/com/idukbaduk/itseats/coupon/controller/CouponController.java
  src/main/java/com/idukbaduk/itseats/coupon/dto/MyCouponDto.java
  src/main/java/com/idukbaduk/itseats/coupon/dto/MyCouponListResponse.java
  src/main/java/com/idukbaduk/itseats/coupon/dto/enums/CouponResponse.java
  src/main/java/com/idukbaduk/itseats/coupon/repository/MemberCouponRepository.java
  src/main/java/com/idukbaduk/itseats/coupon/service/CouponService.java
  src/test/java/com/idukbaduk/itseats/coupon/controller/CouponControllerTest.java
  src/test/java/com/idukbaduk/itseats/coupon/service/CouponServiceTest.java
Labels: feature

#213 [Feature] 가맹점 회원가입 및 로그인 API 분리
  PR_CHANGES.md
  src/main/java/com/idukbaduk/itseats/member/controller/OwnerMemberController.java
  src/main/java/com/idukbaduk/itseats/member/dto/OwnerDto.java
  src/main/java/com/idukbaduk/itseats/member/dto/StoreIdAndStoreNameDto.java
  src/main/java/com/idukbaduk/itseats/member/dto/request/OwnerCreateRequest.java
  src/main/java/com/idukbaduk/itseats/member/dto/response/CurrentOwnerResponse.java
  src/main/java/com/idukbaduk/itseats/member/dto/response/MemberCreateResponse.java
  src/main/java/com/idukbaduk/itseats/member/service/MemberService.java
  src/main/java/com/idukbaduk/itseats/member/service/OwnerMemberService.java
  src/main/java/com/idukbaduk/itseats/store/repository/StoreRepository.java
  src/test/java/com/idukbaduk/itseats/member/service/MemberServiceTest.java
Labels: feature

#227 [Chore] 도커 빌드 설정
  .github/workflows/docker.yml
  Dockerfile
  entrypoint.sh
  src/main/java/com/idukbaduk/itseats/global/config/CorsConfig.java
Labels: chore

#233 [Refactor] 메뉴 목록 조회시 응답 이미지 추가
  src/main/java/com/idukbaduk/itseats/menu/dto/MenuInfoDto.java
  src/main/java/com/idukbaduk/itseats/menu/service/MenuService.java
  src/test/java/com/idukbaduk/itseats/menu/service/MenuServiceTest.java
Labels: refactor

#239 chore: CORS 설정 추가
  src/main/java/com/idukbaduk/itseats/global/config/CorsConfig.java
Labels: chore

#240 [Release] 2025-07-11 13:25
  src/main/java/com/idukbaduk/itseats/global/config/CorsConfig.java
  src/main/java/com/idukbaduk/itseats/menu/dto/MenuInfoDto.java
  src/main/java/com/idukbaduk/itseats/menu/repository/MenuRepository.java
  src/main/java/com/idukbaduk/itseats/menu/service/MenuService.java
  src/main/java/com/idukbaduk/itseats/order/dto/OrderHistoryDto.java
  src/main/java/com/idukbaduk/itseats/order/entity/Order.java
  src/main/java/com/idukbaduk/itseats/review/service/ReviewService.java
  src/test/java/com/idukbaduk/itseats/menu/service/MenuServiceTest.java
Labels: release

#238 [Feature] 전체 쿠폰 목록 조회 API 구현
  src/main/java/com/idukbaduk/itseats/coupon/controller/CouponController.java
  src/main/java/com/idukbaduk/itseats/coupon/dto/CouponResponseDto.java
  src/main/java/com/idukbaduk/itseats/coupon/dto/MyCouponDto.java
  src/main/java/com/idukbaduk/itseats/coupon/dto/enums/CouponResponse.java
  src/main/java/com/idukbaduk/itseats/coupon/service/CouponService.java
  src/test/java/com/idukbaduk/itseats/coupon/controller/CouponControllerTest.java
  src/test/java/com/idukbaduk/itseats/coupon/service/CouponServiceTest.java
Labels: feature

#242 [Refactor] 결제 승인 관련 수정
  src/main/java/com/idukbaduk/itseats/payment/dto/PaymentClientResponse.java
  src/main/java/com/idukbaduk/itseats/payment/dto/PaymentConfirmRequest.java
  src/main/java/com/idukbaduk/itseats/payment/service/PaymentService.java
Labels: refactor

#246 [Refactor] 메뉴 조회 응답 추가
  src/main/java/com/idukbaduk/itseats/menu/dto/MenuDetailResponse.java
  src/main/java/com/idukbaduk/itseats/menu/service/MenuService.java
Labels: refactor

#251 [Fix] Rider 위치 "SRID 4326" 설정 오류 해결
  src/main/java/com/idukbaduk/itseats/rider/entity/Rider.java
Labels: bug

#254 [Fix]: 퀴리문 SRID 4326 설정
  src/main/java/com/idukbaduk/itseats/order/repository/OrderRepository.java
Labels: fix

#226 feat: 토스페이먼츠 결제 통합 및 API 개선
  RIDER_API_SPEC.md
  data.db
  docker-compose.local.yml
  src/main/java/com/idukbaduk/itseats/global/config/ClientConfig.java
  src/main/java/com/idukbaduk/itseats/global/config/CorsConfig.java
  src/main/java/com/idukbaduk/itseats/global/error/core/ErrorResponse.java
  src/main/java/com/idukbaduk/itseats/global/error/handler/GlobalExceptionHandler.java
  src/main/java/com/idukbaduk/itseats/order/dto/OrderCreateResponse.java
  src/main/java/com/idukbaduk/itseats/order/entity/Order.java
  src/main/java/com/idukbaduk/itseats/order/service/OrderService.java
  src/main/java/com/idukbaduk/itseats/payment/controller/PaymentController.java
  src/main/java/com/idukbaduk/itseats/payment/dto/PaymentConfirmRequest.java
  src/main/java/com/idukbaduk/itseats/payment/dto/TossPaymentConfirmRequest.java
  src/main/java/com/idukbaduk/itseats/payment/dto/enums/PaymentResponse.java
  src/main/java/com/idukbaduk/itseats/payment/error/PaymentException.java
  src/main/java/com/idukbaduk/itseats/payment/error/enums/PaymentConfirmErrorCode.java
  src/main/java/com/idukbaduk/itseats/payment/repository/PaymentRepository.java
  src/main/java/com/idukbaduk/itseats/payment/service/PaymentService.java
  src/main/java/com/idukbaduk/itseats/payment/service/client/PaymentClient.java
  src/main/java/com/idukbaduk/itseats/store/controller/StoreController.java
  src/main/java/com/idukbaduk/itseats/store/service/StoreService.java
  src/test/java/com/idukbaduk/itseats/order/service/OrderServiceTest.java
  src/test/java/com/idukbaduk/itseats/payment/service/PaymentOrderIntegrationTest.java
Labels: feature, fix

#256 [Refactor] 리뷰 관련 필드 추가
  src/main/java/com/idukbaduk/itseats/review/dto/MyReviewDto.java
  src/main/java/com/idukbaduk/itseats/review/dto/ReviewDto.java
  src/main/java/com/idukbaduk/itseats/review/service/OwnerReviewService.java
Labels: refactor

#252 [Chore] 성능 테스트 설정
  build.gradle
  docker-compose.local.yml
  grafana-dashboard/k6.json
  grafana-provisioning/dashboards/k6-dashboard.yml
  grafana-provisioning/datasources/prometheus.yml
  prometheus.yml
  scripts/healthcheck.js
  scripts/loadtest.js
  src/main/java/com/idukbaduk/itseats/global/config/SecurityConfig.java
Labels: chore

#260 [Refactor] 가게 상세 정보 조회 리팩터링
  src/main/java/com/idukbaduk/itseats/store/controller/StoreController.java
  src/main/java/com/idukbaduk/itseats/store/service/StoreService.java
Labels: refactor

#259 [Refactor] 리뷰 신고 관련 필드 추가
  src/main/java/com/idukbaduk/itseats/review/dto/ReviewDto.java
  src/main/java/com/idukbaduk/itseats/review/repository/ReviewReportRepository.java
  src/main/java/com/idukbaduk/itseats/review/service/OwnerReviewService.java
  src/test/java/com/idukbaduk/itseats/review/service/OwnerReviewServiceTest.java
Labels: refactor

#255 [Fix] 라이더 내 정보 조회시 Location null 예외 처리
  src/main/java/com/idukbaduk/itseats/member/dto/response/CurrentRiderResponse.java
Labels: fix

#263 [Refactor] 내 쿠폰 조회 시 CouponId 필드 추가
  src/main/java/com/idukbaduk/itseats/coupon/dto/MyCouponDto.java
  src/main/java/com/idukbaduk/itseats/coupon/service/CouponService.java
Labels: refactor

#267 [Refactor] 가게 목록 조회 부하테스트
  scripts/getNearStores.js
  scripts/getStores.js
  src/main/java/com/idukbaduk/itseats/global/util/GeoUtil.java
  src/main/java/com/idukbaduk/itseats/store/repository/StoreRepository.java
  src/main/java/com/idukbaduk/itseats/store/service/StoreService.java
Labels: refactor

#273 [Refactor] 배달 관련 API 보완
  src/main/java/com/idukbaduk/itseats/order/dto/OrderItemDTO.java
  src/main/java/com/idukbaduk/itseats/order/dto/RiderOrderDetailsResponse.java
  src/main/java/com/idukbaduk/itseats/order/service/RiderOrderService.java
  src/test/java/com/idukbaduk/itseats/order/service/RiderOrderServiceTest.java
Labels: refactor

#275 [Chore] JVM 시간대 설정
  entrypoint.sh
Labels: chore

#279 [Fix] 동일 주문의 라이더 배차가 여러 개 생성되는 문제 수정
  src/main/java/com/idukbaduk/itseats/order/controller/RiderOrderController.java
  src/main/java/com/idukbaduk/itseats/rider/repository/RiderAssignmentRepository.java
  src/main/java/com/idukbaduk/itseats/rider/service/RiderService.java
Labels: fix

#280 [Release] 2025-07-15 10:15
  src/main/java/com/idukbaduk/itseats/order/controller/RiderOrderController.java
  src/main/java/com/idukbaduk/itseats/rider/repository/RiderAssignmentRepository.java
  src/main/java/com/idukbaduk/itseats/rider/service/RiderService.java
Labels: release
