Repository Iduk-Baduk/itseats-server, pull requests merged in 2025-06, with the labels that each got.

#8 [Feature] 결제 엔티티 구현
  src/main/java/com/idukbaduk/itseats/payment/entity/Payment.java
  src/main/java/com/idukbaduk/itseats/payment/entity/enums/DeliveryType.java
  src/main/java/com/idukbaduk/itseats/payment/entity/enums/PaymentMethod.java
  src/main/java/com/idukbaduk/itseats/payment/entity/enums/PaymentStatus.java
  src/main/java/com/idukbaduk/itseats/payment/entity/enums/RiderRequestOption.java
Labels: feature

#10 [Feature] 회원 엔티티 구현
  src/main/java/com/idukbaduk/itseats/member/entity/Member.java
  src/main/java/com/idukbaduk/itseats/member/entity/MemberType.java
Labels: feature

#11 [Feature] 회원 주소 엔티티 구현
  src/main/java/com/idukbaduk/itseats/memberaddress/entity/AddressCategory.java
  src/main/java/com/idukbaduk/itseats/memberaddress/entity/MemberAddress.java
Labels: feature

#12 [Feature] 가맹점 엔티티 구현
  src/main/java/com/idukbaduk/itseats/store/entity/BusinessStatus.java
  src/main/java/com/idukbaduk/itseats/store/entity/Store.java
  src/main/java/com/idukbaduk/itseats/store/entity/StoreStatus.java
Labels: feature

#13 [Feature] 리뷰 엔티티 구현
  src/main/java/com/idukbaduk/itseats/review/entity/Review.java
  src/main/java/com/idukbaduk/itseats/review/entity/ReviewImage.java
  src/main/java/com/idukbaduk/itseats/review/entity/enums/MenuLiked.java
Labels: feature

#18 [Feature] 가게 카테고리 엔티티 구현
  src/main/java/com/idukbaduk/itseats/store/entity/StoreCategory.java
Labels: feature

#19 [Feature] 가게 이미지 엔티티 구현
  src/main/java/com/idukbaduk/itseats/store/entity/StoreImage.java
Labels: feature

#21 [Feature] 메뉴 관련 엔티티 구현
  src/main/java/com/idukbaduk/itseats/menu/entity/Menu.java
  src/main/java/com/idukbaduk/itseats/menu/entity/MenuGroup.java
  src/main/java/com/idukbaduk/itseats/menu/entity/MenuImage.java
  src/main/java/com/idukbaduk/itseats/menu/entity/MenuOption.java
  src/main/java/com/idukbaduk/itseats/menu/entity/MenuOptionGroup.java
  src/main/java/com/idukbaduk/itseats/menu/entity/enums/MenuStatus.java
Labels: feature

#25 [Feature] 쿠폰 관련 엔티티 구현
  src/main/java/com/idukbaduk/itseats/coupon/entity/Coupon.java
  src/main/java/com/idukbaduk/itseats/coupon/entity/MemberCoupon.java
  src/main/java/com/idukbaduk/itseats/coupon/entity/PaymentCoupon.java
  src/main/java/com/idukbaduk/itseats/coupon/entity/enums/CouponType.java
  src/main/java/com/idukbaduk/itseats/coupon/entity/enums/TargetType.java
Labels: feature

#26 [Feature] 주문 메뉴 엔티티 구현
  src/main/java/com/idukbaduk/itseats/order/entity/OrderMenu.java
Labels: feature

#27 [Feature] 즐겨찾기 엔티티 추가
  src/main/java/com/idukbaduk/itseats/member/entity/Favorite.java
Labels: feature

#31 [Feature] 라이더 관련 엔티티 구현
  src/main/java/com/idukbaduk/itseats/rider/entity/Rider.java
  src/main/java/com/idukbaduk/itseats/rider/entity/RiderSettlement.java
  src/main/java/com/idukbaduk/itseats/rider/entity/enums/DeliveryMethod.java
  src/main/java/com/idukbaduk/itseats/rider/entity/enums/SettlementStatus.java
Labels: feature

#33 [Feature] 프랜차이즈 엔티티 구현
  src/main/java/com/idukbaduk/itseats/store/entity/Franchise.java
  src/main/java/com/idukbaduk/itseats/store/entity/Store.java
  src/main/java/com/idukbaduk/itseats/store/entity/enums/BusinessStatus.java
  src/main/java/com/idukbaduk/itseats/store/entity/enums/StoreStatus.java
Labels: feature

#37 [Feature] 메뉴 관련 엔티티 연관관계 설정
  .github/PULL_REQUEST_TEMPLATE.md
  src/main/java/com/idukbaduk/itseats/menu/entity/Menu.java
  src/main/java/com/idukbaduk/itseats/menu/entity/MenuGroup.java
  src/main/java/com/idukbaduk/itseats/menu/entity/MenuImage.java
  src/main/java/com/idukbaduk/itseats/menu/entity/MenuOption.java
  src/main/java/com/idukbaduk/itseats/menu/entity/MenuOptionGroup.java
Labels: feature

#38 [Feature] 가맹점 관련 엔티티 연관관계 설정
  src/main/java/com/idukbaduk/itseats/store/entity/Store.java
  src/main/java/com/idukbaduk/itseats/store/entity/StoreImage.java
Labels: feature

#44 [Feature] 회원 관련 엔티티 연관관계 설정
  src/main/java/com/idukbaduk/itseats/member/entity/Favorite.java
  src/main/java/com/idukbaduk/itseats/member/entity/Member.java
  src/main/java/com/idukbaduk/itseats/member/entity/enums/MemberType.java
  src/main/java/com/idukbaduk/itseats/memberaddress/entity/MemberAddress.java
  src/main/java/com/idukbaduk/itseats/memberaddress/entity/enums/AddressCategory.java
Labels: feature

#51 [Feature] 메뉴 조회 기능 구현
  build.gradle
  docker-compose.local.yml
  src/main/java/com/idukbaduk/itseats/menu/controller/MenuController.java
  src/main/java/com/idukbaduk/itseats/menu/dto/MenuInfoDto.java
  src/main/java/com/idukbaduk/itseats/menu/dto/MenuListRequest.java
  src/main/java/com/idukbaduk/itseats/menu/dto/MenuListResponse.java
  src/main/java/com/idukbaduk/itseats/menu/entity/Menu.java
  src/main/java/com/idukbaduk/itseats/menu/error/MenuErrorCode.java
  src/main/java/com/idukbaduk/itseats/menu/error/MenuException.java
  src/main/java/com/idukbaduk/itseats/menu/repository/MenuRepository.java
  src/main/java/com/idukbaduk/itseats/menu/service/MenuService.java
  src/test/java/com/idukbaduk/itseats/menu/service/MenuServiceTest.java
Labels: feature

#57 [Feature] 주문 정보 상세 조회에 필요한 사전 작업 구현
  src/main/java/com/idukbaduk/itseats/member/error/MemberException.java
  src/main/java/com/idukbaduk/itseats/member/error/enums/MemberErrorCode.java
  src/main/java/com/idukbaduk/itseats/member/repository/MemberRepository.java
  src/main/java/com/idukbaduk/itseats/member/service/MemberService.java
  src/main/java/com/idukbaduk/itseats/memberaddress/entity/MemberAddress.java
  src/main/java/com/idukbaduk/itseats/memberaddress/error/MemberAddressException.java
  src/main/java/com/idukbaduk/itseats/memberaddress/error/enums/MemberAddressErrorCode.java
  src/main/java/com/idukbaduk/itseats/memberaddress/repository/MemberAddressRepository.java
  src/main/java/com/idukbaduk/itseats/memberaddress/service/MemberAddressService.java
  src/main/java/com/idukbaduk/itseats/menu/service/MenuService.java
  src/main/java/com/idukbaduk/itseats/store/entity/Store.java
  src/main/java/com/idukbaduk/itseats/store/error/StoreException.java
  src/main/java/com/idukbaduk/itseats/store/error/enums/StoreErrorCode.java
  src/main/java/com/idukbaduk/itseats/store/repository/StoreRepository.java
  src/main/java/com/idukbaduk/itseats/store/service/StoreService.java
  src/test/java/com/idukbaduk/itseats/member/service/MemberServiceTest.java
  src/test/java/com/idukbaduk/itseats/memberaddress/service/MemberAddressServiceTest.java
  src/test/java/com/idukbaduk/itseats/menu/service/MenuServiceTest.java
  src/test/java/com/idukbaduk/itseats/store/service/StoreServiceTest.java
Labels: feature

#58 [Feature] 사용자 메뉴 옵션 조회 기능 구현
  src/main/java/com/idukbaduk/itseats/menu/controller/UserMenuController.java
  src/main/java/com/idukbaduk/itseats/menu/dto/UserMenuOptionResponse.java
  src/main/java/com/idukbaduk/itseats/menu/dto/UserOptionDto.java
  src/main/java/com/idukbaduk/itseats/menu/dto/UserOptionGroupDto.java
  src/main/java/com/idukbaduk/itseats/menu/entity/MenuOption.java
  src/main/java/com/idukbaduk/itseats/menu/entity/MenuOptionGroup.java
  src/main/java/com/idukbaduk/itseats/menu/error/MenuErrorCode.java
  src/main/java/com/idukbaduk/itseats/menu/repository/MenuImageRepository.java
  src/main/java/com/idukbaduk/itseats/menu/repository/MenuOptionGroupRepository.java
  src/main/java/com/idukbaduk/itseats/menu/repository/MenuOptionRepository.java
  src/main/java/com/idukbaduk/itseats/menu/repository/MenuRepository.java
  src/main/java/com/idukbaduk/itseats/menu/service/UserMenuService.java
  src/test/java/com/idukbaduk/itseats/menu/service/MenuServiceTest.java
  src/test/java/com/idukbaduk/itseats/menu/service/UserMenuServiceTest.java
Labels: feature

#65 [Feature] 주소 추가 API 구현
  src/main/java/com/idukbaduk/itseats/memberaddress/controller/MemberAddressController.java
  src/main/java/com/idukbaduk/itseats/memberaddress/dto/AddressCreateRequest.java
  src/main/java/com/idukbaduk/itseats/memberaddress/dto/AddressCreateResponse.java
  src/main/java/com/idukbaduk/itseats/memberaddress/dto/enums/AddressResponse.java
  src/main/java/com/idukbaduk/itseats/memberaddress/service/MemberAddressService.java
  src/test/java/com/idukbaduk/itseats/memberaddress/service/MemberAddressServiceTest.java
Labels: feature

#68 [Feature] 가게 별 리뷰 목록 조회 API 구현
  src/main/java/com/idukbaduk/itseats/review/controller/ReviewController.java
  src/main/java/com/idukbaduk/itseats/review/dto/StoreReviewDto.java
  src/main/java/com/idukbaduk/itseats/review/dto/StoreReviewResponse.java
  src/main/java/com/idukbaduk/itseats/review/entity/Review.java
  src/main/java/com/idukbaduk/itseats/review/error/ReviewErrorCode.java
  src/main/java/com/idukbaduk/itseats/review/error/ReviewException.java
  src/main/java/com/idukbaduk/itseats/review/repository/ReviewImageRepository.java
  src/main/java/com/idukbaduk/itseats/review/repository/ReviewRepository.java
  src/main/java/com/idukbaduk/itseats/review/service/ReviewService.java
  src/test/java/com/idukbaduk/itseats/review/service/ReviewServiceTest.java
Labels: feature

#71 [Feature] 가게 전체 목록 조회 API 구현
  src/main/java/com/idukbaduk/itseats/review/repository/ReviewRepository.java
  src/main/java/com/idukbaduk/itseats/store/controller/StoreController.java
  src/main/java/com/idukbaduk/itseats/store/dto/StoreDto.java
  src/main/java/com/idukbaduk/itseats/store/dto/StoreListResponse.java
  src/main/java/com/idukbaduk/itseats/store/entity/StoreImage.java
  src/main/java/com/idukbaduk/itseats/store/repository/StoreImageRepository.java
  src/main/java/com/idukbaduk/itseats/store/repository/StoreRepository.java
  src/main/java/com/idukbaduk/itseats/store/service/StoreService.java
  src/test/java/com/idukbaduk/itseats/store/service/StoreServiceTest.java
Labels: feature

#74 [Feature] 가게 정보 조회 API 구현
  src/main/java/com/idukbaduk/itseats/member/repository/FavoriteRepository.java
  src/main/java/com/idukbaduk/itseats/review/repository/ReviewRepository.java
  src/main/java/com/idukbaduk/itseats/store/controller/StoreController.java
  src/main/java/com/idukbaduk/itseats/store/dto/StoreDetailResponse.java
  src/main/java/com/idukbaduk/itseats/store/repository/StoreImageRepository.java
  src/main/java/com/idukbaduk/itseats/store/repository/StoreRepository.java
  src/main/java/com/idukbaduk/itseats/store/service/StoreService.java
  src/test/java/com/idukbaduk/itseats/store/service/StoreServiceTest.java
Labels: feature

#82 [Fix] 순환 참조 문제 해결 및 테스트 코드 수정
  src/main/java/com/idukbaduk/itseats/memberaddress/service/MemberAddressService.java
  src/main/java/com/idukbaduk/itseats/order/service/OrderService.java
  src/main/java/com/idukbaduk/itseats/payment/service/PaymentService.java
  src/test/java/com/idukbaduk/itseats/memberaddress/service/MemberAddressServiceTest.java
  src/test/java/com/idukbaduk/itseats/order/service/OrderServiceTest.java
  src/test/java/com/idukbaduk/itseats/payment/service/PaymentServiceTest.java
Labels: fix

#85 [Feature] 메뉴 그룹 설정 API 구현
  src/main/java/com/idukbaduk/itseats/global/JpaConfig.java
  src/main/java/com/idukbaduk/itseats/menu/controller/MenuController.java
  src/main/java/com/idukbaduk/itseats/menu/dto/MenuGroupDto.java
  src/main/java/com/idukbaduk/itseats/menu/dto/MenuGroupRequest.java
  src/main/java/com/idukbaduk/itseats/menu/dto/MenuGroupResponse.java
  src/main/java/com/idukbaduk/itseats/menu/dto/enums/MenuResponse.java
  src/main/java/com/idukbaduk/itseats/menu/entity/MenuGroup.java
  src/main/java/com/idukbaduk/itseats/menu/repository/MenuGroupRepository.java
  src/main/java/com/idukbaduk/itseats/menu/repository/MenuRepository.java
  src/main/java/com/idukbaduk/itseats/menu/service/MenuGroupService.java
  src/main/java/com/idukbaduk/itseats/menu/service/MenuService.java
  src/test/java/com/idukbaduk/itseats/menu/controller/MenuControllerTest.java
  src/test/java/com/idukbaduk/itseats/menu/service/MenuGroupServiceTest.java
  src/test/java/com/idukbaduk/itseats/menu/service/MenuServiceTest.java
Labels: feature

#87 [Feature] 가맹점 대시보드 조회(홈 화면) API 구현
  src/main/java/com/idukbaduk/itseats/order/entity/Order.java
  src/main/java/com/idukbaduk/itseats/order/repository/OrderRepository.java
  src/main/java/com/idukbaduk/itseats/store/controller/OwnerStoreController.java
  src/main/java/com/idukbaduk/itseats/store/dto/StoreDashboardResponse.java
  src/main/java/com/idukbaduk/itseats/store/service/OwnerStoreService.java
  src/test/java/com/idukbaduk/itseats/store/controller/StoreDashboardControllerTest.java
  src/test/java/com/idukbaduk/itseats/store/service/StoreDashboardServiceTest.java
Labels: feature

#91 [Feature] 배달 수락 API 구현
  src/main/java/com/idukbaduk/itseats/order/entity/Order.java
  src/main/java/com/idukbaduk/itseats/order/entity/enums/OrderStatus.java
  src/main/java/com/idukbaduk/itseats/order/error/enums/OrderErrorCode.java
  src/main/java/com/idukbaduk/itseats/rider/controller/RiderController.java
  src/main/java/com/idukbaduk/itseats/rider/dto/enums/RiderResponse.java
  src/main/java/com/idukbaduk/itseats/rider/service/RiderService.java
  src/test/java/com/idukbaduk/itseats/rider/controller/RiderControllerTest.java
  src/test/java/com/idukbaduk/itseats/rider/service/RiderServiceTest.java
Labels: feature

#93 [Feature] 메뉴 그룹 목록 조회 API 구현
  src/main/java/com/idukbaduk/itseats/menu/controller/MenuController.java
  src/main/java/com/idukbaduk/itseats/menu/dto/MenuGroupDto.java
  src/main/java/com/idukbaduk/itseats/menu/dto/enums/MenuResponse.java
  src/main/java/com/idukbaduk/itseats/menu/service/MenuGroupService.java
  src/test/java/com/idukbaduk/itseats/menu/controller/MenuControllerTest.java
  src/test/java/com/idukbaduk/itseats/menu/service/MenuGroupServiceTest.java
Labels: feature

#97 [Feature] 배달 완료 API 구현
  src/main/java/com/idukbaduk/itseats/order/entity/Order.java
  src/main/java/com/idukbaduk/itseats/order/entity/enums/OrderStatus.java
  src/main/java/com/idukbaduk/itseats/order/repository/OrderRepository.java
  src/main/java/com/idukbaduk/itseats/rider/controller/RiderController.java
  src/main/java/com/idukbaduk/itseats/rider/dto/enums/RiderResponse.java
  src/main/java/com/idukbaduk/itseats/rider/service/RiderService.java
  src/test/java/com/idukbaduk/itseats/rider/controller/RiderControllerTest.java
  src/test/java/com/idukbaduk/itseats/rider/service/RiderServiceTest.java
Labels: feature

#96 [Feature] 주문 접수 조회 API 구현
  src/main/java/com/idukbaduk/itseats/order/controller/OwnerOrderController.java
  src/main/java/com/idukbaduk/itseats/order/dto/OrderReceptionDTO.java
  src/main/java/com/idukbaduk/itseats/order/dto/OrderReceptionResponse.java
  src/main/java/com/idukbaduk/itseats/order/dto/enums/OrderResponse.java
  src/main/java/com/idukbaduk/itseats/order/entity/Order.java
  src/main/java/com/idukbaduk/itseats/order/repository/OrderRepository.java
  src/main/java/com/idukbaduk/itseats/order/service/OwnerOrderService.java
  src/main/java/com/idukbaduk/itseats/store/service/OwnerStoreService.java
  src/test/java/com/idukbaduk/itseats/order/controller/OwnerOrderControllerTest.java
  src/test/java/com/idukbaduk/itseats/order/service/OwnerOrderServiceTest.java
  src/test/java/com/idukbaduk/itseats/store/service/OwnerStoreServiceTest.java
Labels: feature

#98 [Fix] MySQL POINT 자료형 사용을 위한 설정
  build.gradle
  src/main/java/com/idukbaduk/itseats/global/util/GeoUtil.java
  src/main/java/com/idukbaduk/itseats/memberaddress/dto/AddressCreateRequest.java
  src/main/java/com/idukbaduk/itseats/memberaddress/entity/MemberAddress.java
  src/main/java/com/idukbaduk/itseats/memberaddress/service/MemberAddressService.java
  src/main/java/com/idukbaduk/itseats/order/entity/Order.java
  src/main/java/com/idukbaduk/itseats/rider/entity/Rider.java
  src/main/java/com/idukbaduk/itseats/store/entity/Store.java
  src/main/java/com/idukbaduk/itseats/store/service/OwnerStoreService.java
  src/test/java/com/idukbaduk/itseats/memberaddress/service/MemberAddressServiceTest.java
  src/test/java/com/idukbaduk/itseats/order/service/OrderServiceTest.java
  src/test/java/com/idukbaduk/itseats/store/service/OwnerStoreServiceTest.java
Labels: fix

#106 [Feature] 라이더 주문 정보 조회 API 구현
  src/main/java/com/idukbaduk/itseats/order/controller/RiderOrderController.java
  src/main/java/com/idukbaduk/itseats/order/dto/OrderDetailsResponse.java
  src/main/java/com/idukbaduk/itseats/order/dto/OrderItemDTO.java
  src/main/java/com/idukbaduk/itseats/order/dto/enums/OrderResponse.java
  src/main/java/com/idukbaduk/itseats/order/service/RiderOrderService.java
  src/test/java/com/idukbaduk/itseats/order/controller/RiderOrderControllerTest.java
  src/test/java/com/idukbaduk/itseats/order/service/RiderOrderServiceTest.java
Labels: feature

#105 [Feature] 주문 수락 API 구현
  src/main/java/com/idukbaduk/itseats/order/controller/OwnerOrderController.java
  src/main/java/com/idukbaduk/itseats/order/dto/OrderAcceptResponse.java
  src/main/java/com/idukbaduk/itseats/order/dto/enums/OrderResponse.java
  src/main/java/com/idukbaduk/itseats/order/entity/enums/OrderStatus.java
  src/main/java/com/idukbaduk/itseats/order/error/enums/OrderErrorCode.java
  src/main/java/com/idukbaduk/itseats/order/service/OwnerOrderService.java
  src/test/java/com/idukbaduk/itseats/order/controller/OwnerOrderControllerTest.java
  src/test/java/com/idukbaduk/itseats/order/service/OwnerOrderServiceTest.java
Labels: feature

#101 [Feature] 가맹점 주문 상세 조회 API 구현
  src/main/java/com/idukbaduk/itseats/order/controller/OwnerOrderController.java
  src/main/java/com/idukbaduk/itseats/order/dto/OrderDetailResponse.java
  src/main/java/com/idukbaduk/itseats/order/dto/OrderMenuItemDTO.java
  src/main/java/com/idukbaduk/itseats/order/repository/OrderRepository.java
  src/main/java/com/idukbaduk/itseats/order/service/OwnerOrderService.java
  src/test/java/com/idukbaduk/itseats/order/controller/OwnerOrderControllerTest.java
  src/test/java/com/idukbaduk/itseats/order/service/OwnerOrderServiceTest.java
  src/test/java/com/idukbaduk/itseats/store/service/StoreDashboardServiceTest.java
  src/test/java/com/idukbaduk/itseats/store/service/StoreServiceTest.java
Labels: feature

#115 [Feature] 조리 완료 API 구현
  src/main/java/com/idukbaduk/itseats/order/controller/OwnerOrderController.java
  src/main/java/com/idukbaduk/itseats/order/dto/OrderCookedResponse.java
  src/main/java/com/idukbaduk/itseats/order/dto/enums/OrderResponse.java
  src/main/java/com/idukbaduk/itseats/order/service/OwnerOrderService.java
  src/test/java/com/idukbaduk/itseats/order/controller/OwnerOrderControllerTest.java
  src/test/java/com/idukbaduk/itseats/order/service/OwnerOrderServiceTest.java
Labels: feature

#112 [Feature] 주문 거절 API 구현
  src/main/java/com/idukbaduk/itseats/order/controller/OwnerOrderController.java
  src/main/java/com/idukbaduk/itseats/order/dto/OrderRejectRequest.java
  src/main/java/com/idukbaduk/itseats/order/dto/OrderRejectResponse.java
  src/main/java/com/idukbaduk/itseats/order/dto/enums/OrderResponse.java
  src/main/java/com/idukbaduk/itseats/order/entity/Order.java
  src/main/java/com/idukbaduk/itseats/order/service/OwnerOrderService.java
  src/test/java/com/idukbaduk/itseats/order/controller/OwnerOrderControllerTest.java
  src/test/java/com/idukbaduk/itseats/order/service/OwnerOrderServiceTest.java
Labels: feature

#122 [Feature] 가맹점 메뉴 상세 조회 API 구현
  src/main/java/com/idukbaduk/itseats/menu/controller/MenuController.java
  src/main/java/com/idukbaduk/itseats/menu/dto/MenuDetailResponse.java
  src/main/java/com/idukbaduk/itseats/menu/dto/enums/MenuResponse.java
  src/main/java/com/idukbaduk/itseats/menu/error/MenuErrorCode.java
  src/main/java/com/idukbaduk/itseats/menu/repository/MenuRepository.java
  src/main/java/com/idukbaduk/itseats/menu/service/MenuService.java
  src/test/java/com/idukbaduk/itseats/menu/controller/MenuDetailControllerTest.java
  src/test/java/com/idukbaduk/itseats/menu/service/MenuDetailServiceTest.java
Labels: feature

#119 [Feature] 메뉴 수정 API 구현
  src/main/java/com/idukbaduk/itseats/menu/controller/MenuController.java
  src/main/java/com/idukbaduk/itseats/menu/dto/MenuRequest.java
  src/main/java/com/idukbaduk/itseats/menu/dto/enums/MenuResponse.java
  src/main/java/com/idukbaduk/itseats/menu/entity/Menu.java
  src/main/java/com/idukbaduk/itseats/menu/entity/MenuGroup.java
  src/main/java/com/idukbaduk/itseats/menu/entity/MenuImage.java
  src/main/java/com/idukbaduk/itseats/menu/entity/MenuOption.java
  src/main/java/com/idukbaduk/itseats/menu/entity/MenuOptionGroup.java
  src/main/java/com/idukbaduk/itseats/menu/repository/MenuGroupRepository.java
  src/main/java/com/idukbaduk/itseats/menu/repository/MenuImageRepository.java
  src/main/java/com/idukbaduk/itseats/menu/repository/MenuOptionRepository.java
  src/main/java/com/idukbaduk/itseats/menu/repository/MenuRepository.java
  src/main/java/com/idukbaduk/itseats/menu/service/MenuGroupService.java
  src/main/java/com/idukbaduk/itseats/menu/service/MenuMediaService.java
  src/main/java/com/idukbaduk/itseats/menu/service/MenuService.java
  src/main/java/com/idukbaduk/itseats/menu/service/UserMenuService.java
  src/test/java/com/idukbaduk/itseats/menu/controller/MenuControllerTest.java
  src/test/java/com/idukbaduk/itseats/menu/service/MenuServiceTest.java
Labels: feature

#123 [Feature] 메뉴 삭제 API 구현
  src/main/java/com/idukbaduk/itseats/menu/controller/MenuController.java
  src/main/java/com/idukbaduk/itseats/menu/dto/enums/MenuResponse.java
  src/main/java/com/idukbaduk/itseats/menu/entity/Menu.java
  src/main/java/com/idukbaduk/itseats/menu/service/MenuService.java
  src/test/java/com/idukbaduk/itseats/menu/service/MenuServiceTest.java
Labels: feature

#127 [Feature] 라이더 배달 거절 API 구현
  src/main/java/com/idukbaduk/itseats/menu/controller/MenuController.java
  src/main/java/com/idukbaduk/itseats/menu/dto/enums/MenuResponse.java
  src/main/java/com/idukbaduk/itseats/rider/controller/RiderController.java
  src/main/java/com/idukbaduk/itseats/rider/dto/RejectDeliveryResponse.java
  src/main/java/com/idukbaduk/itseats/rider/dto/RejectReasonRequest.java
  src/main/java/com/idukbaduk/itseats/rider/dto/enums/RiderResponse.java
  src/main/java/com/idukbaduk/itseats/rider/entity/RiderAssignment.java
  src/main/java/com/idukbaduk/itseats/rider/entity/enums/AssignmentStatus.java
  src/main/java/com/idukbaduk/itseats/rider/error/enums/RiderErrorCode.java
  src/main/java/com/idukbaduk/itseats/rider/repository/RiderAssignmentRepository.java
  src/main/java/com/idukbaduk/itseats/rider/service/RiderService.java
  src/test/java/com/idukbaduk/itseats/rider/controller/RiderControllerTest.java
  src/test/java/com/idukbaduk/itseats/rider/service/RiderServiceTest.java
Labels: feature

#129 [Feature] S3 파일 업로드 설정
  build.gradle
  src/main/java/com/idukbaduk/itseats/global/S3Config.java
  src/main/java/com/idukbaduk/itseats/menu/error/MenuErrorCode.java
  src/main/java/com/idukbaduk/itseats/menu/service/MenuMediaService.java
Labels: feature

#131 [Feature] 가게 카테고리 자동 생성
  src/main/java/com/idukbaduk/itseats/StoreCategoryInitializer.java
Labels: feature

#133 [Feature] 배달 요청 조회 API 구현
  src/main/java/com/idukbaduk/itseats/order/controller/RiderOrderController.java
  src/main/java/com/idukbaduk/itseats/order/dto/OrderRequestResponse.java
  src/main/java/com/idukbaduk/itseats/order/dto/enums/OrderResponse.java
  src/main/java/com/idukbaduk/itseats/order/repository/OrderRepository.java
  src/main/java/com/idukbaduk/itseats/order/service/RiderOrderService.java
  src/main/java/com/idukbaduk/itseats/rider/error/enums/RiderErrorCode.java
  src/main/java/com/idukbaduk/itseats/rider/service/RiderService.java
  src/test/java/com/idukbaduk/itseats/order/controller/RiderOrderControllerTest.java
  src/test/java/com/idukbaduk/itseats/order/service/RiderOrderServiceTest.java
  src/test/java/com/idukbaduk/itseats/rider/service/RiderServiceTest.java
Labels: feature

#134 [Feature] JWT 토큰 발행 기능 구현
  build.gradle
  docker-compose.local.yml
  src/main/java/com/idukbaduk/itseats/ItseatsServerApplication.java
  src/main/java/com/idukbaduk/itseats/auths/controller/AuthController.java
  src/main/java/com/idukbaduk/itseats/auths/service/AuthService.java
  src/main/java/com/idukbaduk/itseats/external/jwt/config/JwtTokenProperties.java
  src/main/java/com/idukbaduk/itseats/external/jwt/entity/enums/JwtTokenType.java
  src/main/java/com/idukbaduk/itseats/external/jwt/error/JwtTokenException.java
  src/main/java/com/idukbaduk/itseats/external/jwt/error/enums/JwtTokenErrorCode.java
  src/main/java/com/idukbaduk/itseats/external/jwt/service/JwtTokenRepository.java
  src/main/java/com/idukbaduk/itseats/external/jwt/service/JwtTokenRepositoryImpl.java
  src/main/java/com/idukbaduk/itseats/external/jwt/service/JwtTokenService.java
  src/main/java/com/idukbaduk/itseats/external/redis/config/RedisConfig.java
  src/main/java/com/idukbaduk/itseats/external/redis/config/RedisProperties.java
  src/main/java/com/idukbaduk/itseats/external/redis/repository/RedisKeyValueRepository.java
  src/main/java/com/idukbaduk/itseats/global/util/ClockUtil.java
  src/main/java/com/idukbaduk/itseats/member/repository/MemberRepository.java
Labels: feature

#141 [Feature] 이미지 업로드 기능 구현
  src/main/java/com/idukbaduk/itseats/global/util/S3Utils.java
  src/main/java/com/idukbaduk/itseats/menu/service/MenuMediaService.java
  src/main/java/com/idukbaduk/itseats/order/error/enums/OrderErrorCode.java
  src/main/java/com/idukbaduk/itseats/order/service/RiderImageService.java
  src/main/java/com/idukbaduk/itseats/store/controller/OwnerStoreController.java
  src/main/java/com/idukbaduk/itseats/store/dto/StoreCreateRequest.java
  src/main/java/com/idukbaduk/itseats/store/error/enums/StoreErrorCode.java
  src/main/java/com/idukbaduk/itseats/store/service/OwnerStoreService.java
  src/main/java/com/idukbaduk/itseats/store/service/StoreMediaService.java
  src/test/java/com/idukbaduk/itseats/store/controller/OwnerStoreControllerTest.java
  src/test/java/com/idukbaduk/itseats/store/service/OwnerStoreServiceTest.java
Labels: feature

#140 [Feature] 매장 상태 변경 API 구현
  src/main/java/com/idukbaduk/itseats/store/controller/OwnerStoreController.java
  src/main/java/com/idukbaduk/itseats/store/dto/StoreStatusUpdateRequest.java
  src/main/java/com/idukbaduk/itseats/store/dto/StoreStatusUpdateResponse.java
  src/main/java/com/idukbaduk/itseats/store/dto/enums/StoreResponse.java
  src/main/java/com/idukbaduk/itseats/store/entity/Store.java
  src/main/java/com/idukbaduk/itseats/store/service/OwnerStoreService.java
  src/test/java/com/idukbaduk/itseats/store/controller/OwnerStoreControllerTest.java
  src/test/java/com/idukbaduk/itseats/store/service/OwnerStoreServiceTest.java
Labels: feature

#143 [Feature] 고객 회원가입 기능 구현
  src/main/java/com/idukbaduk/itseats/member/controller/MemberController.java
  src/main/java/com/idukbaduk/itseats/member/dto/CustomerDto.java
  src/main/java/com/idukbaduk/itseats/member/dto/enums/MemberResponse.java
  src/main/java/com/idukbaduk/itseats/member/dto/request/CustomerCreateRequest.java
  src/main/java/com/idukbaduk/itseats/member/dto/response/CustomerCreateResponse.java
  src/main/java/com/idukbaduk/itseats/member/entity/Member.java
  src/main/java/com/idukbaduk/itseats/member/error/enums/MemberErrorCode.java
  src/main/java/com/idukbaduk/itseats/member/repository/MemberRepository.java
  src/main/java/com/idukbaduk/itseats/member/service/MemberService.java
  src/main/java/com/idukbaduk/itseats/member/util/PasswordUtil.java
  src/test/java/com/idukbaduk/itseats/member/factory/MemberTestFactory.java
  src/test/java/com/idukbaduk/itseats/member/service/MemberServiceTest.java
Labels: feature

#148 [Refactor] 가게 목록 및 상세 조회 리팩터링
  src/main/java/com/idukbaduk/itseats/menu/repository/MenuImageRepository.java
  src/main/java/com/idukbaduk/itseats/store/dto/MenuImageWithStoreId.java
  src/main/java/com/idukbaduk/itseats/store/dto/PointDto.java
  src/main/java/com/idukbaduk/itseats/store/dto/StoreDetailResponse.java
  src/main/java/com/idukbaduk/itseats/store/dto/StoreDto.java
  src/main/java/com/idukbaduk/itseats/store/service/StoreService.java
  src/test/java/com/idukbaduk/itseats/order/service/RiderImageServiceTest.java
  src/test/java/com/idukbaduk/itseats/store/service/StoreServiceTest.java
Labels: refactor

#149 [Feature] Swagger 적용
  src/main/java/com/idukbaduk/itseats/global/config/SecurityConfig.java
  src/main/java/com/idukbaduk/itseats/global/config/SwaggerConfig.java
Labels: feature
